### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'base_directory'

### ISSUE THREAD

**Issue by Jelloeater** [Jelloeater/mineOSHeartBeat#4]
Found @ 19461773cc5f326126c2d9adc5be7ac92fd8b432
Traceback (most recent call last):
  File "/srv/mineOSHeartBeat/mineos_monitor.py", line 314, in <module>
    main()
  File "/srv/mineOSHeartBeat/mineos_monitor.py", line 113, in main
    multi_server_mode.start()
  File "/srv/mineOSHeartBeat/mineos_monitor.py", line 193, in start
    server(i).check_server()
  File "/srv/mineOSHeartBeat/mineos_monitor.py", line 295, in check_server
    self.start_server()
  File "/srv/mineOSHeartBeat/mineos_monitor.py", line 300, in start_server
    self.start()
  File "/usr/games/minecraft/mineos.py", line 43, in wrapper
    fn(self, _args, *_kwargs)
  File "/usr/games/minecraft/mineos.py", line 63, in wrapper
    fn(self, _args, *_kwargs)
  File "/usr/games/minecraft/mineos.py", line 343, in start
    if self.port in [s.port for s in self.list_ports_up()]:
  File "/usr/games/minecraft/mineos.py", line 1254, in list_ports_up
    instance = cls(name, base_directory=base_dir)
TypeError: **init**() got an unexpected keyword argument 'base_directory'

**Comment by Jelloeater** [comment]
See commit 969e14d3acc6b241e093b1549f76738564668894 for details
Don't know how to fix, and It's not the end of the world that we cannot to things this way.

**Comment by hexparrot** [comment]
You actually can just leave out **init** and it will automatically use the parent class' **init**

**Comment by Jelloeater** [comment]
Thanks for the fix!
